#home:
#    path: /
#    controller: App\Controller\HomeController::home
user:
  type: rest
  resource: App\Controller\UserController

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
